{% block SERVICE_DNS_SETTINGS %}
{%- if SERVICES[service]['subdomains'] %}
{{ "dns_search:"|indent(8,true) + SERVICES[service]['subdomains'][0]|indent(30,true) + "." + DOMAIN }}
{%- endif %}
{%- if 'vpn' in service %}
{{ "dns:"|indent(8, true) }}
{%- for nameserver in SERVICES[service]['DNS'] %}
{{ "- "|indent(10, true) + nameserver }}
{%- endfor %}
{%- elif (SERVICES[service]['networks']) and not SERVICES[service]['networks']['vpn']) and not (SERVICES[service]['OAUTH_PROXY'] or SERVICES[service]['proxy_secrets']) %}
{{ "domainname:"|indent(8, true) + DOMAIN|default("localhost")|indent(30, true) }}
{{ "dns:"|indent(8, true) }}
{%- if not SERVICES[service]['DNS'] %}
{%- for nameserver in defaults.DNS %}
{{ "- "|indent(10, true) + nameserver }}
{%- endfor %}
{%- else %}
{%- for nameserver in SERVICES[service]['DNS'] %}
{{ "- "|indent(10, true) + nameserver }}
{%- endfor %}
{%- endif %}
{%- endif %}
{{ super() }}
{% endblock %}
